### ISSUE TITLE
Naming questions

### ISSUE THREAD

**Issue by ManWithBear** [Showmax/SHMTableView#1]
1. SHMTableView name can confuse people, that it child of UITableView. IMHO "TableAdapter" name is more clear.
2. Why you use lowercase names for types in generics? It's confusing and against Swift API Design Guidelines
`SHMTableRow<cell: SHMConfigurableRow>`

**Comment by LukasKorba** [comment]
ad 2: Fixed, thanks for feedback.

ad 1: You're right, formaly it's not a `view` based class. We've discussed it a lot and we're still convinced the SHMTableView sounds better as any Table<whatever> thing. The connection is so tight so users know what can expect and what can achieve within this library. The fact is not a child of UITableView doesn't force users to any specific issue.
